import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "./../lib/utils";
import { Toaster } from "@/components/ui/toaster";
import 'react-day-picker/dist/style.css';
import ReactQueryProvider from "@/provider/ReactQueryProvider";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
	title: "Noteams - Best Tools for Teams",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={cn(inter.className)}>
				
				<main>
					<ReactQueryProvider>

					{children}
					</ReactQueryProvider>
					</main>
				<Toaster />
			</body>
		</html>
	);
}
